---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    author: dorothy
    name: postgres-service
spec:
  ports:
    - ports: 5432
      targetPort: 5432
  selector:
    author: dorothy
      name: postgres-pod
...